### ISSUE TITLE
Smarter QueryColumn

### ISSUE THREAD

**Issue by shaunpearsondev** [danielearwicker/flowerbi#45]
Hey,

Continuing on with the idea of making the schema smarter I would love to get your thoughts on the following:

Adding "filters" and "aggregations" as arrays onto QueryColumn and also adding inheritance to this class, this would allow smarter autocomplete like only having an `Min and Max` Operator if the type is `number | Date` and also allowing a Filters to only show you relevant operators to the data type

I have put together a PoC here to allow you to get my initial though on how to approach this:

https://github.com/bigwhitesolutions/reporting/blob/d34cee72cad58ef7dcee9a04e602b7ce1021eb05/React/frontend/src/QueryColumn-Extensions.ts

Inheritance flow
```
 BasicQueryColumn => ArrayQueryColumn
 BasicQueryColumn => DateQueryColumn => NumberQueryColumn
 ```

**Comment by danielearwicker** [comment]
This makes sense, though it can be a bit simpler because only the `sum` and `avg` methods need to be on a derived `NumericQueryColumn` type. The other aggregations work on all types. Also the `in` filter isn't restricted by the column type being an array (column types can only be simple SQL types) but lets you do a filter such as `WHERE MyInt IN (1, 2, 4)`.

**Comment by danielearwicker** [comment]
See release 3.2.0
